export const BOTAO_CLICADOSCCESS = 'BOTAO_CLICADOSCCESS';
export const BOTAO_CLICADOREQUEST = 'BOTAO_CLICADOREQUEST';
export const BOTAO_CLICADOFAIL = 'BOTAO_CLICADOFAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_UPDATED_SUCCESS = 'REGISTER_UPDATED_SUCCESS';
export const REGISTER_CREATED_SUCCESS = 'REGISTER_CREATED_SUCCESS';

export const PERSISTREHYDRATE = 'persist/REHYDRATE';
